### ISSUE TITLE
Prototype: Death Screen (ASAP)

### ISSUE THREAD

**Issue by RealDealLea1** [RealDealLea1/canyonsCSclub#46]
Make a simple death screen that tells the player that they are dead. 
and would allow the player to:
-Restart
-End game ( to Main Menu)

**Comment by Evanito** [comment]
https://i.imgur.com/Hkh550B.png my prototype idea, a little reminiscent of minecraft

**Comment by Tb64** [comment]
Game Over Text Tutorial: 

https://unity3d.com/learn/tutorials/projects/space-shooter-tutorial/ending-game?playlist=17147

https://unity3d.com/learn/tutorials/tic-tac-toe/game-over-text?playlist=17111

**Comment by Tb64** [comment]
Closed Old Project
