### ISSUE TITLE
Prototype: Main menu (ASAP)

### ISSUE THREAD

**Issue by Tb64** [RealDealLea1/canyonsCSclub#8]
Need a basic main menu, a place where we can change controls would be great.  Also audio controls would be great too.

Prototype should haveat least:
-Start Game
-Options
-Exit

https://unity3d.com/learn/tutorials/topics/user-interface-ui/creating-main-menu?playlist=17111

**Comment by RealDealLea1** [comment]
added to working prototype on MAR6...super simple tho

**Comment by Tb64** [comment]
Closed Old Project
